### ISSUE TITLE
Analyse des traces 

### ISSUE THREAD

**Issue by lrassindrame** [lrassindrame/Case_study_renting#8]
(quelle colonne correspond à l'ID du cas, à l'activité, au timestamp) et informations supplémentaires (ressources, coût, opérateur...)

**Comment by Valmort17** [comment]
On observe plusieurs types de données dans les fichiers : les données sur les "trace" qui contiennent des "event". 
### Trace : 
- **@@case_index**
- **case**
- **concept name**
- yearsOfEducation
- german speaking
- age
- gender
- citizen
- protected
- married

### Event : 
- **@@index**
- **activity / concept:name**
- resource
- **time / time:timestamp**

On a donc 

| -                    | Event    |
| -------------- |  --------|
| ID Utilisateur | index    |
| Activité          | activity |
| Timestamp    | time     |

Des facteurs comme 'Age', 'citizen', 'German speaking', 'gender', 'religious affiliation', et 'yearsOfEducation' peuvent influencer le processus de location, ce qui peut donner lieu à des discriminations.
