### ISSUE TITLE
Statistiques

### ISSUE THREAD

**Issue by lrassindrame** [lrassindrame/Case_study_renting#9]
(nombre de cas/traces, nombre de variantes, nombre de cas par variante, nombre moyen d’activités par cas, nombre minimum et maximum d’activités, durée min-max-moyenne, statistiques utilisant les ressources...)

**Comment by Valmort17** [comment]
Plusieurs statistiques ont été calculées sur tous les fichiers présents dans le dossier `datasets` : 
- Number of cases
- Number of events
- Number of variants
- Number of activities
- Start activities
- End activities
- Number of activities per variant
- List of activities per case
- Activities per case (min/max/avg)
- Case duration (min/max/avg)
- Number of times that a resource is used
- Cycle time 
- Rework (when the same activity is repeated in the same case)
- Case duration

**Comment by Valmort17** [comment]
On doit visualiser des critères discriminants (taux succès selon genre, ethnie...) avec des graphes pour soutenir nos propos

**Comment by Valmort17** [comment]
On pourrait plaquer l'affichage des statistiques sur un plan compris entre 0 et 1 pour avoir une vraie vision sur des statistiques.. L'échelle monte jusqu'à ~3.5, ce qui biaise un peu pour des pourcentages...
